# -*- coding: utf-8 -*-
"""XGBoost

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MDcgtITW622EcMl-DfZcWt_qN77O8rqj
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from xgboost import XGBRegressor

# 데이터 불러오기
df = pd.read_csv("preprocessed_with_cluster_ALL.csv")

# REGION 제거
if "REGION" in df.columns:
    df = df.drop(columns=["REGION"])

# 주요 결측 제거
df = df.dropna(subset=[
    "DGSTFN", "VISIT_AREA_NM", "MAIN_TRAVEL_MONTH", "MVMN_NM",
    "REVISIT_INTENTION", "RCMDTN_INTENTION", "RELATION_TYPE",
    "VISIT_AREA_TYPE_CD"
])

# 타겟과 피처 분리
X_reg = df.drop(columns=[
    "DGSTFN", "label", "TRAVELER_ID", "TRAVEL_ID",
    "REVISIT_INTENTION", "RCMDTN_INTENTION",
    "TRAVEL_START_YMD", "TRAVEL_END_YMD", "CLUSTER"
], errors="ignore")

y_reg = df["DGSTFN"]

# 범주형/수치형 변수 분리
cat_features = [
    "VISIT_AREA_NM", "MAIN_TRAVEL_MONTH", "TRAVEL_STATUS_ACCOMPANY",
    "RELATION_TYPE", "MVMN_NM", "GENDER", "AGE_GRP", "VISIT_AREA_TYPE_CD"
]

num_features = [
    "TRAVEL_STYL_1", "TRAVEL_STYL_3", "TRAVEL_STYL_5",
    "TRAVEL_STYL_6", "TRAVEL_STYL_7", "TRAVEL_STYL_8"
]

# ColumnTransformer 설정
preprocessor = ColumnTransformer([
    ("cat", OneHotEncoder(handle_unknown="ignore"), cat_features),
    ("num", "passthrough", num_features)
], remainder="drop")  # 나머지는 제거

# 전체 파이프라인 구성
reg_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", XGBRegressor(
        objective="reg:squarederror",
        n_estimators=100,
        max_depth=5,
        learning_rate=0.1,
        random_state=42
    ))
])

# 학습/테스트 분할
X_train, X_test, y_train, y_test = train_test_split(
    X_reg, y_reg, test_size=0.3, random_state=42
)

# 학습 및 예측
reg_pipeline.fit(X_train, y_train)
y_pred = reg_pipeline.predict(X_test)

# 평가 결과 출력
print("\n📊 XGBoost Regression (with TRAVEL_STYLE)")
print("✅ MAE:", round(mean_absolute_error(y_test, y_pred), 4))
print("✅ MSE:", round(mean_squared_error(y_test, y_pred), 4))
print("✅ R² :", round(r2_score(y_test, y_pred), 4))